name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/jobs/build.yml

  preview:
    name: Deploy Preview
    needs: build
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Deploy Production to Vercel
        uses: amondnet/vercel-action@v42
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.WRITE_TOKEN }}
          vercel-org-id: ${{ env.VERCEL_ORG_ID }}
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID }}
          target: preview
          prebuilt: true
          vercel-output-dir: dist/
