name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/jobs/build.yml

  preview:
    name: Deploy Preview
    needs: build
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
